name = "OptimalApplication"
uuid = "3e920f78-0eb2-4966-9e73-7442414dae3e"
authors = ["Max Kapur <maxkapur@gmail.com> and contributors"]
version = "0.2.1"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"
Aqua = "0.8"
Combinatorics = "1"
DataStructures = "0.18"
Random = "1"
Test = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua"]
