name: Run tests
on: [push, pull_request]

jobs:
  RunTests:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ["1.10", "1"] # Test against LTS and current minor release
        os: [ubuntu-latest, macOS-latest, windows-latest]
        arch: [x64]

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Build package
        uses: julia-actions/julia-buildpkg@v1

      - name: Run unit tests
        uses: julia-actions/julia-runtest@v1
